### ISSUE TITLE
Adds optionally the initial level when levels are available

### ISSUE THREAD

**Issue by gfronza** [clappr/clappr-level-selector-plugin#13]
The rtmp plugin has options to indicate the ```startLevel (levelId)``` and ```autoSwitch (true/false)```. This should somehow reflect on the level selector, right? how could we do that? Playbacks could expose those information as properties, or the event ```PLAYBACK_LEVELS_AVAILABLE``` could take them.

Does that make sense to you?

**Comment by leandromoreira** [comment]
We initially think of starting always in `AUTO` because it makes sense for the most of the playbacks. But since RTMP handles it differently we can:

For `startLevel`:

* call `rtmp.currentLevel = initial` after triggering PLAYBACK_LEVELS_AVAILABLE  on rtmp_playback, forcing it to change since it's a behavior specific for it **or**
* change `PLAYBACK_LEVELS_AVAILABLE` event signature adding `{levels: [], initialState: x}` and change in all the playbacks (hls.js, flashls, dash...)

For the `autoSwitch` I guess it's safe to assume it's `AUTO = -1` option, so when:
> skips the calling `rtmp.currentLevel = initial` after triggering PLAYBACK_LEVELS_AVAILABLE if autoSwitch is true otherwise calls it with the value passed startLevel (or take the first one)

What do you think?

**Comment by gfronza** [comment]
I decided to remove the options autoSwitch after all. We can assume that when ```startLevel``` is not ```-1```,  the playback is in manual mode.

As for the ```startLevel```. It would work better if we could change the ```PLAYBACK_LEVELS_AVAILABLE``` event signature as you proposed. Because setting ```currentLevel = initial``` would force an unnecessary transition, as opposed to setting the ```RESOURCE_INITIAL_INDEX``` which starts the streaming at the startLevel.

Can we do that?

Thanks!

**Comment by leandromoreira** [comment]
:) yes @gfronza, let's just wait a few days more because we're preparing a clappr release!

**Comment by gfronza** [comment]
@leandromoreira :+1: great!!

**Comment by leandromoreira** [comment]
@gfronza I'm gonna start this soon :) since we just released https://github.com/clappr/clappr/releases/tag/0.2.24

**Comment by gfronza** [comment]
@leandromoreira awesome! Now I can use the new events! :) BTW the new ```.configure({...})``` method is a blessing!! :)

**Comment by leandromoreira** [comment]
@gfronza I also think we also should add optional bitrate: `{id: number, label: x, bitrate: 300000}`

**Comment by leandromoreira** [comment]
f1577de

**Comment by gfronza** [comment]
@leandromoreira what's your angle on adding bitrate in the levels list? Would be as a fallback for missing label?

**Comment by leandromoreira** [comment]
I didn't it :P 
https://github.com/clappr/clappr/blob/master/src/base/events.js#L361-L370
