### ISSUE TITLE
Fix the streaming quality

### ISSUE THREAD

**Issue by alouane** [clappr/clappr-level-selector-plugin#37]
Is it possible to fix the quality of a streaming (m3u8), like to be set always on level id 3?
Because I noticed that each time the streaming is changing its quality, the video freeze for like 1s but the audio continue
I'm testing on a android device, the web version is working properly!

**Comment by leandromoreira** [comment]
@alouane I once faced a similar issue at that time I found out that my stream (hls) was misconfigured, you can run a check stream tool, in the end the [PTS](https://en.wikipedia.org/wiki/Presentation_timestamp) among the qualities were misaligned.

> Is it possible to fix the quality of a streaming (m3u8), like to be set always on level id 3?

I don't think so, mostly because usually the playback starts with the lowest bitrate (the first on the playlist) and then the adaptive algorithm will take cpu, bandwidth, dropped frames and so on to promote or demote the levels.

Just do a check on your hls stream also always using the level 3, shouldn't be better to have only a single quality then?

**Comment by alouane** [comment]
OK I see, you are right, probably the stream is misconfigured.
Can you help me with a link (or a tool) where I can check the stream health (http://alaoulainter-tv.scdn.arkena.com/alaoulainter.isml/index.m3u8)?

**Comment by leandromoreira** [comment]
What you can do is to use `mediainfo` (download one ts from each quality and run on them). While I googled it I found:

https://github.com/epiclabs-io/hls-analyzer (which seems easy to use and shows many problems)

And apple also has one tool for this mediastreamvalidator

**Comment by alouane** [comment]
Thanks a lot @leandromoreira for your help, great tool! I appreciate it
Cheers
